spring:
  datasource:
    url: jdbc:sqlserver://sqlmkide.database.windows.net:1433;database=SqlTest;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: mkide1
    password: Raashi@12
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191


